(* SME-NI of P1||(P2||P3): true *)

Require Export refine.
Require Export parser.

Definition P123: IA := parse
"IA 
[WAIT_SS_WFAR_S_HP_F_T, WAIT_SS_WFAR_S_CONRS_F_T, WAIT_SS_WFAR_S_DA_F_T, 
 WAIT_SS_WFAR_S_DISC_F_T, WAIT_SS_CONN_S_DISC_S_T, WAIT_SS_WFAR_S_IDLE_T, 
 IDLE_SS_IDLE_S_DISC_S_T, WAIT_SS_DISC_1_S_DISC_S_T, WAIT_SS_WFAR_S_DA_S_T, 
 WAIT_SS_DISC_1_S_HP_F_T, WAIT_SS_CONF_S_HP_F_T, WAIT_SS_DISC_1_S_CONRS_F_T, 
 WAIT_SS_CONF_S_CONRS_F_T, WAIT_SS_DISC_1_S_DA_F_T, WAIT_SS_CONF_S_DA_F_T, 
 WAIT_SS_DISC_1_S_DISC_F_T, WAIT_SS_CONF_S_DISC_F_T, WAIT_SS_DISC_1_S_IDLE_T, 
 WAIT_SS_CONF_S_IDLE_T, WAIT_SS_WFTC_S_HP_F_T, WAIT_SS_WFTC_S_CONRS_F_T, 
 WAIT_SS_WFTC_S_DA_F_T, WAIT_SS_WFTC_S_DISC_F_T, WAIT_SS_WFTC_S_IDLE_T, 
 WAIT_SS_WFTC_S_CONR_S_T, WAIT_SS_CONN_S_HP_F_T, WAIT_SS_CONN_S_DISC_F_T, 
 WAIT_SS_CONN_S_DA_F_T, WAIT_SS_CONN_S_CONRS_F_T, IDLE_SS_IDLE_S_HP_F_T, 
 IDLE_SS_IDLE_S_CONRS_F_T, IDLE_SS_IDLE_S_DA_F_T, IDLE_SS_IDLE_S_DISC_F_T, 
 IDLE_SS_IDLE_S_IDLE_T, WAIT_SS_CONN_S_IDLE_T] 
(IDLE_SS_IDLE_S_IDLE_T) 
[T_DISC_req_F, T_DATA_req_F, T_CONN_resp_F, T_HPDATA_req_F] 
[T_CONN_ind_F, T_DATA_ind_F, T_DISC_ind_F, T_HPDATA_ind_F] 
[e, T_DATA_req_S, T_HPDATA_req_S, T_DISC_req_S, T_CONN_req_S, T_HPDATA_ind_S, 
 T_CONN_conf_S, T_DATA_ind_S, T_DISC_ind_S, Sa_DATA_req_S, Sa_HPDATA_req_S, 
 Sa_DISC_req_S, Sa_CONN_req_S, Sa_DATA_ind_S, Sa_HPDATA_ind_S, Sa_DISC_ind_S, Sa_CONN_conf_S] 
[IDLE_SS_IDLE_S_IDLE_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_IDLE_T, 
IDLE_SS_IDLE_S_IDLE_T->(T_DISC_req_F)IDLE_SS_IDLE_S_DISC_F_T, 
IDLE_SS_IDLE_S_IDLE_T->(T_DATA_req_F)IDLE_SS_IDLE_S_DA_F_T, 
IDLE_SS_IDLE_S_IDLE_T->(T_CONN_resp_F)IDLE_SS_IDLE_S_CONRS_F_T, 
IDLE_SS_IDLE_S_IDLE_T->(T_HPDATA_req_F)IDLE_SS_IDLE_S_HP_F_T, 
IDLE_SS_IDLE_S_CONRS_F_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_CONRS_F_T, 
IDLE_SS_IDLE_S_DA_F_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_DA_F_T, 
IDLE_SS_IDLE_S_DISC_F_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_DISC_F_T, 
IDLE_SS_IDLE_S_HP_F_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_HP_F_T, 
WAIT_SS_CONN_S_IDLE_T->(T_DISC_req_F)WAIT_SS_CONN_S_DISC_F_T, 
WAIT_SS_CONN_S_IDLE_T->(T_DATA_req_F)WAIT_SS_CONN_S_DA_F_T, 
WAIT_SS_CONN_S_IDLE_T->(T_CONN_resp_F)WAIT_SS_CONN_S_CONRS_F_T, 
WAIT_SS_CONN_S_IDLE_T->(T_HPDATA_req_F)WAIT_SS_CONN_S_HP_F_T, 
WAIT_SS_CONN_S_IDLE_T->(T_CONN_req_S)WAIT_SS_WFTC_S_CONR_S_T, 
WAIT_SS_WFTC_S_CONR_S_T->(T_CONN_ind_F)WAIT_SS_WFTC_S_IDLE_T, 
WAIT_SS_WFTC_S_IDLE_T->(T_DISC_req_F)WAIT_SS_WFTC_S_DISC_F_T, 
WAIT_SS_WFTC_S_IDLE_T->(T_DATA_req_F)WAIT_SS_WFTC_S_DA_F_T, 
WAIT_SS_WFTC_S_IDLE_T->(T_CONN_resp_F)WAIT_SS_WFTC_S_CONRS_F_T, 
WAIT_SS_WFTC_S_IDLE_T->(T_HPDATA_req_F)WAIT_SS_WFTC_S_HP_F_T, 
WAIT_SS_WFTC_S_CONRS_F_T->(T_CONN_conf_S)WAIT_SS_CONF_S_IDLE_T, 
WAIT_SS_WFTC_S_DISC_F_T->(T_DISC_ind_S)WAIT_SS_DISC_1_S_IDLE_T, 
WAIT_SS_DISC_1_S_IDLE_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_IDLE_T, 
WAIT_SS_CONF_S_IDLE_T->(T_DISC_req_F)WAIT_SS_CONF_S_DISC_F_T, 
WAIT_SS_DISC_1_S_IDLE_T->(T_DISC_req_F)WAIT_SS_DISC_1_S_DISC_F_T, 
WAIT_SS_CONF_S_IDLE_T->(T_DATA_req_F)WAIT_SS_CONF_S_DA_F_T, 
WAIT_SS_DISC_1_S_IDLE_T->(T_DATA_req_F)WAIT_SS_DISC_1_S_DA_F_T, 
WAIT_SS_CONF_S_IDLE_T->(T_CONN_resp_F)WAIT_SS_CONF_S_CONRS_F_T, 
WAIT_SS_DISC_1_S_IDLE_T->(T_CONN_resp_F)WAIT_SS_DISC_1_S_CONRS_F_T, 
WAIT_SS_CONF_S_IDLE_T->(T_HPDATA_req_F)WAIT_SS_CONF_S_HP_F_T, 
WAIT_SS_DISC_1_S_IDLE_T->(T_HPDATA_req_F)WAIT_SS_DISC_1_S_HP_F_T, 
WAIT_SS_CONF_S_IDLE_T->(T_DATA_req_S)WAIT_SS_WFAR_S_DA_S_T, 
WAIT_SS_CONF_S_IDLE_T->(T_DISC_req_S)WAIT_SS_DISC_1_S_DISC_S_T, 
WAIT_SS_DISC_1_S_CONRS_F_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_CONRS_F_T, 
WAIT_SS_DISC_1_S_DA_F_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_DA_F_T, 
WAIT_SS_DISC_1_S_DISC_F_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_DISC_F_T, 
WAIT_SS_DISC_1_S_DISC_S_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_DISC_S_T, 
WAIT_SS_DISC_1_S_HP_F_T->(Sa_DISC_ind_S)IDLE_SS_IDLE_S_HP_F_T, 
WAIT_SS_WFAR_S_DA_S_T->(T_DATA_ind_F)WAIT_SS_WFAR_S_IDLE_T, 
WAIT_SS_DISC_1_S_DISC_S_T->(T_DISC_ind_F)WAIT_SS_DISC_1_S_IDLE_T, 
IDLE_SS_IDLE_S_DISC_S_T->(Sa_CONN_req_S)WAIT_SS_CONN_S_DISC_S_T, 
IDLE_SS_IDLE_S_DISC_S_T->(T_DISC_ind_F)IDLE_SS_IDLE_S_IDLE_T, 
WAIT_SS_WFAR_S_IDLE_T->(T_DISC_req_F)WAIT_SS_WFAR_S_DISC_F_T, 
WAIT_SS_WFAR_S_IDLE_T->(T_DATA_req_F)WAIT_SS_WFAR_S_DA_F_T, 
WAIT_SS_WFAR_S_IDLE_T->(T_CONN_resp_F)WAIT_SS_WFAR_S_CONRS_F_T, 
WAIT_SS_WFAR_S_IDLE_T->(T_HPDATA_req_F)WAIT_SS_WFAR_S_HP_F_T, 
WAIT_SS_CONN_S_DISC_S_T->(T_DISC_ind_F)WAIT_SS_CONN_S_IDLE_T, 
WAIT_SS_CONN_S_DISC_S_T->(e)WAIT_SS_DISC_1_S_IDLE_T, 
WAIT_SS_WFAR_S_DISC_F_T->(T_DISC_ind_S)WAIT_SS_DISC_1_S_IDLE_T]".

Definition P123_hid: IA :=
 IAutomaton.hiding P123 (ASet.GenActs [&"T_HPDATA_req_F", &"T_HPDATA_ind_F"]).

Definition P123_rep: IA :=
 IAutomaton.hiding
 ( IAutomaton.replacement P123 (&"tau") (ASet.GenActs [&"T_HPDATA_req_F"]) )
 (ASet.GenActs [&"T_HPDATA_ind_F"]).

Eval compute in :> P123_hid.
Eval compute in :> P123_rep.
(* Eval compute in (TSet.cardinal (IAutomaton.get_trans (P123_hid))). 48 *)
Eval compute in SMENI_refinement_bounded P123_rep P123_hid 24.
